version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    env_file: .env
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist && \
             npm install && \
             npm run production && \
             php artisan config:clear && \
             php artisan key:generate && \
             php artisan migrate --force && \
             php artisan db:seed --force && \
             chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && \
             chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && \
             apache2-foreground"
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=pesquisa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - laravel

networks:
  laravel:

volumes:
  postgres_data:
