services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pesquisa
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    command: >
      sh -c "/wait-for-it.sh db:5432 -- php artisan migrate --force &&
            php artisan db:seed --force &&
            apache2-foreground"
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=pesquisa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  postgres_data:
