<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Congregation extends Model
{
    use HasFactory;

    protected $fillable = [
        'nome_principal',
        'nomes_alternativos',
        'siglas',
        'familia_final',
        'genero',
        'fontes',
        'data_aprovacao_constituicoes',
        'data_aprovacao_regras',
        'data_aprovacao_dir_diocesano',
        'data_aprovacao_dir_pontificio',
        'data_aprovacao_decretum_laudis',
        'anos_reformulacao_constituicoes',
        'situacao_canonica',
        'data_fundacao',
        'pais_fundacao',
        'cidade_fundacao',
        'chegada_brasil_estado',
        'chegada_brasil_municipio',
        'membros_brasil',
        'irmaos_as',
        'postulantes',
        'novicos',
        'carisma',
        'motivos_vinda',
        'pais_presente',
        'estados_presente',
        'tem_formulario_preenchido',
        'existe',
        'existe_brasil',
        'possui_mantenedora',
        'fundadores_m',
        'fundadores_f',
        'com_hierarquia_m',
        'com_hierarquia_f',
        'sem_hierarquia_m',
        'sem_hierarquia_f',
        'santo_m',
        'santo_f',
        'nomes_fundadores',
        'datas_aprovacao',
        'periodo_funcionamento_casas_brasil',
        'periodo_funcionamento_casas_fechadas',
        'num_estados_presente',
        'num_casas_mundo',
        'num_paises_presente',
        'membros_brasil_ac2015',
        'sacerdotes',
        'dados_alternativos',
        'membros_mundo_total',
        'org_hierarquica_nomeacao',
        'org_hierarquica_eleicao',
        'org_hierarquica_ambos',
        'publicacoes_uso_interno',
        'publicacoes_livres',
        'total_publicacoes',
        'obras_sobre_congregacao',
        'total',
        'num_fontes_manuscritas',
        'taxa_reproducao',
        'missao_fundacao',
        'missao_hoje',
        'trabalhos_assumidos',
        'notas',
        'sede_brasil_cidade',
        'sede_brasil_estado',
        'sede_brasil_capital',
    ];
}
